### ISSUE TITLE
Public functions calls

### ISSUE THREAD

**Issue by PennyScripter** [dereuromark/cakephp-tinyauth#23]
I have in my controller functions not related to views. If I do not include them in the acl.ini it is firing the flash auth message when my javascript calls this functions for ajax updates. Is there a way to exclude these functions from the acl.ini? Should these be private functions _someFunction()?

Kinda new at this...

**Comment by dereuromark** [comment]
If you call them from the view via ajax this is nothing different from normal actions.
So either they are public or not.
If you want them public, use Auth->allow() as documented to exclude them from auth.

**Comment by ionas** [comment]
What you want to do is treat them as normal methods (because they expose information to the outside world) in terms of authorization, as @dereuromark explained. If you don't want those functions to be accessible beyond XHR (e.g. ajax) requests, then you want to use `$this->request->is('ajax')` checks (afair).

That aside this is not a help forum and that's rather a question, so I encourage you to join us on IRC irc://irc.freenode.net/#cakephp utilize the book, the API and check stack overflow and google groups.
